"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createCategory = exports.updateTournament = exports.listMyTournaments = exports.createTournament = exports.adminDeleteUser = exports.adminUpdateUser = exports.adminSetGlobalRole = exports.adminListUsers = exports.completeProfile = exports.health = void 0;
var health_1 = require("./handlers/health");
Object.defineProperty(exports, "health", { enumerable: true, get: function () { return health_1.health; } });
var complete_profile_1 = require("./handlers/auth/complete-profile");
Object.defineProperty(exports, "completeProfile", { enumerable: true, get: function () { return complete_profile_1.completeProfile; } });
var list_users_1 = require("./handlers/admin/list-users");
Object.defineProperty(exports, "adminListUsers", { enumerable: true, get: function () { return list_users_1.adminListUsers; } });
var set_global_role_1 = require("./handlers/admin/set-global-role");
Object.defineProperty(exports, "adminSetGlobalRole", { enumerable: true, get: function () { return set_global_role_1.adminSetGlobalRole; } });
var update_user_1 = require("./handlers/admin/update-user");
Object.defineProperty(exports, "adminUpdateUser", { enumerable: true, get: function () { return update_user_1.adminUpdateUser; } });
var delete_user_1 = require("./handlers/admin/delete-user");
Object.defineProperty(exports, "adminDeleteUser", { enumerable: true, get: function () { return delete_user_1.adminDeleteUser; } });
var create_tournament_1 = require("./handlers/tournament/create-tournament");
Object.defineProperty(exports, "createTournament", { enumerable: true, get: function () { return create_tournament_1.createTournament; } });
var list_my_tournaments_1 = require("./handlers/tournament/list-my-tournaments");
Object.defineProperty(exports, "listMyTournaments", { enumerable: true, get: function () { return list_my_tournaments_1.listMyTournaments; } });
var update_tournament_1 = require("./handlers/tournament/update-tournament");
Object.defineProperty(exports, "updateTournament", { enumerable: true, get: function () { return update_tournament_1.updateTournament; } });
var create_category_1 = require("./handlers/category/create-category");
Object.defineProperty(exports, "createCategory", { enumerable: true, get: function () { return create_category_1.createCategory; } });
//# sourceMappingURL=index.js.map